// Generated by CoffeeScript 1.6.3
(function() {
  var app, compile, express, nib, route, stylus;

  express = require("express");

  stylus = require("stylus");

  nib = require("nib");

  route = require("./routes");

  app = express();

  compile = function(str, path) {
    return stylus(str).set("filename", path).use(nib());
  };

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.use(express.logger("dev"));

  app.use(stylus.middleware({
    src: __dirname + "/public",
    compile: compile
  }));

  app.use(express["static"](__dirname + "/public"));

  app.use(express.bodyParser());

  app.get("/", route.index);

  app.get("/partials/:name", route.partials);

  app.use(function(req, res, next) {
    res.status(404);
    if (req.accepts("html")) {
      res.render("partials/404", {
        url: req.url,
        title: "Oh no!"
      });
      return;
    }
    if (req.accepts("json")) {
      res.send({
        error: "Not found"
      });
      return;
    }
    return res.type("txt").send("Not found");
  });

  app.listen(8123);

  console.log("Node @ http:#localhost:8123...\n");

}).call(this);
